### ISSUE TITLE
JayData/Mongo (odata-server) update (MERGE) not working as expected.

### ISSUE THREAD

**Issue by arnos** [jaystack/jaydata#99] opened 2013-05-21 02:11 UTC
I've setup a server using the odata-server npm package. I found what seems to be a minor issue when updating an entity with an reference to another entity.

When you insert (POST) a new entity with a referral to a new or an existing entity the code works as expected and you see both the navigation property and the corresponding __id populated in mongoDB.

When you update (MERGE) an existing entity with a referral to a new or an existing entity the code seems to only do half of the job. I see the navigation properly populated but the corresponding __id remains "null".

In the screenshot below of mongo "AdmtDr" is populated, but the corresponding "AdmtDr__id" is null. But when you do an insert both fields are properly populated.

![screen shot 2013-05-20 at 10 08 13 pm](https://f.cloud.github.com/assets/989874/539541/15bdfbe8-c1bb-11e2-8c57-9d9a4faa10a9.png)

**Comment by robesz** [comment] 2013-05-21 05:02
Hi Arnos,

Could you please share the code of your which creates and inserts the entity?

Thanks

**Comment by robesz** [comment] 2013-05-23 11:49
Hello, any updates? Did you manage to resolve the issue? We are here to help you, but we need to see the code how you update the entity.

**Comment by arnos** [comment] 2013-05-23 12:58
Sorry for the delay I haven't been able to figure it out more.

My client code that works by creating two entities (creates a $batch post with POST entries for both entities), as expected MongoDB entry has AdmtDr__ID and AdmtDr populated, and the expand works

``` javascript
        $data.service(url, function(contextFactory, contextType){
            var db = contextFactory();
            db.onReady(function(){
              db.toh_odata_staff.toArray(function (staff) {
                  var dr = staff[0]
                  var encounter = new db.encounters.elementType({ AdmtDr: dr });
                  db.encounters.add(encounter)
                  db.saveChanges(function () {
                  db.encounter.include('Staff').toArray(function (p) { console.log(p);});
                });
              });
        });
```

My client code that works by creating one entity and linking it to the an existing one, as expected MongoDB entry has AdmtDr__ID and AdmtDr populated, and the expand works

creates an HTTP POST request with payload:

``` javascript
\\ staff Id is NTE5Y2JiNTRlNTQ3YzVhNDA0MDAwMDQx
{"AdmtDr":{"__metadata":{"uri":"toh_odata_staff('NTE5Y2JiNTRlNTQ3YzVhNDA0MDAwMDQx')"}}}
```

Code:

``` javascript
        $data.service(url, function(contextFactory, contextType){
            var db = contextFactory();
            db.onReady(function(){
           db.toh_odata_staff.toArray(function (staff) {
                          var dr = staff[0]
              db.toh_odata_staff.attach(dr);
              var encounter = new db.encounters.elementType({ AdmtDr: dr });
              db.toh_odata_encntrs.attach(encounter);
              encounter.save();
          });
           });
            });
```

But what doesn't work when linking two exisiting entities creates a Merge request with the following payload, as expected MongoDB entry with AdmtDr populated but AdmtDr__Id is still null, and the expand returns the toh_odata_staff json object but all the fields are blank

This creates an HTTP MERGE request with payload:

``` javascript
\\ encounter Id is NTE5Y2JiNTRlNTQ3YzVhNDA0MDAwMDJj
\\ staff Id is NTE5Y2JiNTRlNTQ3YzVhNDA0MDAwMDQx
{"Id":"NTE5Y2JiNTRlNTQ3YzVhNDA0MDAwMDJj","AdmtDr":{"__metadata":{"uri":"toh_odata_staff('NTE5Y2JiNTRlNTQ3YzVhNDA0MDAwMDQx')"}}}
```

Code:

``` javascript
        $data.service(url, function(contextFactory, contextType){
            var db = contextFactory();
            db.onReady(function(){
           db.toh_odata_staff.toArray(function (staff) {
           db.toh_odata_encntrs.toArray(function (encounters) {
                          var dr = staff[0]
              db.toh_odata_staff.attach(dr);
              var encounter = encounters[0];
              db.toh_odata_encntrs.attach(encounter1);
              encounter.AdmtDr = dr;
              encounter.save();
          });
           });
            });
        });
```

**Comment by agdolla** [comment] 2013-05-23 14:12
Hi!
ItemStore API is for simple use cases, for navigation use JSQL. So instead of encounter.save(); call db.saveChanges(). Also please add fail() branches so any error can be logged like:

``` javascript
db.saveChanges()
.then(function() { console.log('ok'); })
.fail(function(reason) { console.log('not ok', reason); })
```

**Comment by arnos** [comment] 2013-05-23 15:58
Yes it's a simplistic use case, and it fails

Modified code to use db.saveChanges() it ran, no errors: but MongoDB still has the AdmtDr__id field as null and AdmtDr is populated with a pointer to toh_odata_staff , and ObjectId('NTE5Y2JiNTRlNTQ3YzVhNDA0MDAwMDQx').

The HTTP MERGE request had the following payload:

``` javascript
{"Id":"NTE5Y2JiNTRlNTQ3YzVhNDA0MDAwMDJk","AdmtDr":{"__metadata":{"uri":"toh_odata_staff('NTE5Y2JiNTRlNTQ3YzVhNDA0MDAwMDQx')"}}}
```

And here's the code that ran

``` javascript
       $data.service(url, function(contextFactory, contextType){
            var db = contextFactory();
            db.onReady(function(){
           db.toh_odata_staff.toArray(function (staff) {
                          var dr = staff[0]
              db.toh_odata_staff.attach(dr);
              var encounter = new db.encounters.elementType({ AdmtDr: dr });
              db.toh_odata_encntrs.attach(encounter);
              db.saveChanges()
.then(function() { console.log('ok'); })
.fail(function(reason) { console.log('not ok', reason); })
          });
           });
            });
```

If I run an expand on toh_odata_encntrs I get the following under encntr > AdmtDr, as you can see from the server side there is no id value in the metadata (although 'NTE5Y2JiNTRlNTQ3YzVhNDA0MDAwMDQx' was assigned and is present in the AdmtDr field in MongoDb)

``` javascript
AdmtDr":{"__metadata":{"id":"http://10.247.5.139:8080/data/toh_odata_staff()","uri":"http://10.247.5.139:8080/data/toh_odata_staff()","type":"odata.Staff"}
```

**Comment by robesz** [comment] 2013-05-29 17:14
Thanks for the detailed description of the issue, @arnos !
This was a bug in MongoDB Provider 1.3.0, the OData part was working fine, MongoDB provider did save the navigation fields but failed in case an update.
We were able to reproduce the problem and the issue has already been fixed in the development branch and will be released with 1.3.1 soon.

Thank you again for the detailed report.
Robert

**Closed as completed by robesz** 2013-05-29 17:14 UTC

**Comment by hschaefer123** [comment] 2014-01-17 18:37
Hi Robert,
is this issue really fixed inside 1.3.1?

I just started playing around with OpenUI5 (sap user interface lib heavily focused on odata) and node -> odata-server.

I can create new entries and also delete existing entries.

Currently the update will not work the same way as above!

I am trying to different kinds of updates.

1) model.submitChange

PUT http://localhost:8888/todo/Todos('NTJkOTc1MDhiZDA5MzA1MDFhNzBlN2U5') 404 (Not Found) 

This kind of request is rejected by odata-server!

2)  model.submitChanges

POST http://localhost:8888/todo/Todos('NTJkOTc1MDhiZDA5MzA1MDFhNzBlN2U5') 500 (Internal Server Error) 

## Request Header:

Accept:application/atom+xml,application/atomsvc+xml,application/xml
Accept-Encoding:gzip,deflate,sdch
Accept-Language:de
Connection:keep-alive
Content-Length:539
Content-Type:application/atom+xml
DataServiceVersion:2.0
Host:localhost:8888
MaxDataServiceVersion:2.0
Origin:http://localhost:8888
Referer:http://localhost:8888/ui/index.html
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.76 Safari/537.36

## x-http-method:MERGE

## Request Payload

## <a:entry xmlns:a="http://www.w3.org/2005/Atom" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices"><a:author><a:name/>/a:author<a:category term="Todo" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme"/><a:content type="application/xml"><m:properties><d:Id>NTJkOTc1MDhiZDA5MzA1MDFhNzBlN2U5/d:Id<d:Task>Hallo/d:Task<d:DueDate>2014-01-17T18:23:04.560/d:DueDate<d:Completed>false/d:Completed/m:properties/a:content/a:entry

## Error

2014-01-17 19:32:32 The following problem occurred: HTTP request failed500,Internal Server Error,MongoError: E11000 duplicate key error index: TodoDatabase.Todos.$_id_  dup key: { : ObjectId('52d97508bd0930501a70e7e9') }
    at Object.toError (D:\UI5\UO5\node_modules\odata-server\node_modules\mongodb\lib\mongodb\utils.js:110:11)
    at D:\UI5\UO5\node_modules\odata-server\node_modules\mongodb\lib\mongodb\collection\core.js:212:24
    at Server.Base._callHandler (D:\UI5\UO5\node_modules\odata-server\node_modules\mongodb\lib\mongodb\connection\base.js:442:41)
    at D:\UI5\UO5\node_modules\odata-server\node_modules\mongodb\lib\mongodb\connection\server.js:485:18
    at MongoReply.parseBody (D:\UI5\UO5\node_modules\odata-server\node_modules\mongodb\lib\mongodb\responses\mongo_reply.js:68:5)
    at null.&lt;anonymous&gt; (D:\UI5\UO5\node_modules\odata-server\node_modules\mongodb\lib\mongodb\connection\server.js:443:20)
    at EventEmitter.emit (events.js:95:17)
    at null.&lt;anonymous&gt; (D:\UI5\UO5\node_modules\odata-server\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:191:13)
    at EventEmitter.emit (events.js:98:17)
    at Socket.&lt;anonymous&gt; (D:\UI5\UO5\node_modules\odata-server\node_modules\mongodb\lib\mongodb\connection\connection.js:418:22) -  

For me it seems to be the same error as described above.

Currently it seems, that the odata-server has not been updated for some month.
Is the Project currently and actively under development?

Cheers Holger

**Comment by tfitting** [comment] 2014-12-19 08:23
Hi Holger,
in UI5 youneed to use the parameter "merge" in your update request.

```
    oModel.update(
        sPath,
        mPayload,
        {
            success : jQuery.proxy(cb_success, this),
            error : jQuery.proxy(cb_error, this),
            *merge: true*
        }
    );
```

sadly jaydata does create a duplicate key error. i am still fighting to bring jaydata and ui5 together.

see:
http://stackoverflow.com/questions/22838096/odata-jaydata-odata-update-request-returns-error-404-sapui5-node

Best
Thomas

**Comment by hschaefer123** [comment] 2014-12-22 08:44
Hi Robert,
good to know, that you are also looking on UI5.

For SAP oData is the first class Communication Stack.

By the way. SAP is currently adding something called "OData4SAP" as an annotation layer to oData. This is a custom namespace that will be recognized by UI5 oData Model.

In Future Directions something like ValueHelps or Analytical Tables/Drilldowns will be able out-of-the-box on analyzing depended Metadata.

If someone would be able to interject custom annonations to Jaydata this would be also a great help to be able to add something similar to your lib.

A usecase is to dynamically generate a table:

```
      var oModel = new sap.ui.model.odata.ODataModel(".../salesOrders.xsodata/", true);       

      //Table Column Definitions
      var oMeta = oModel.getServiceMetadata();
      var oControl;          
      for ( var i = 0; i < oMeta.dataServices.schema[0].entityType[0].property.length; i++) {
          var property = oMeta.dataServices.schema[0].entityType[0].property[i];

          oControl = new sap.ui.commons.TextField().bindProperty("value",property.name);
          oTable.addColumn(new sap.ui.table.Column({label:new sap.ui.commons.Label({text: property.name}), template: oControl, sortProperty: property.name, filterProperty: property.name, filterOperator: sap.ui.model.FilterOperator.EQ, flexible: true, width: "125px" }));
      }         
```

OData4SAP is generating annotations like sap-label, etc. but also more complex Type like DIMENSIONS, MEASSURES to be able to use it in Business Warehouse Topics.

Maybe this info is useful for you too.

Thanks for taking time to answering.

Cheers Holger
